apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: devozs
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb: # Deploying a new cluster
      database: greenics
      owner: app
      secret:
        name: app-auth
